### PR TITLE
Vert.x e2e tests patch

### PR DESCRIPTION
**Pull request by akoniar**

### CODE REVIEW

**Comment by Ladicek** [comment]
This is supposed to emulate Launcher. I asked internally whether Launcher changed or supports both, because this is news to me. In the meantime, I'd prefer not to merge this.

**Comment by Ladicek** [comment]
It seems renaming from `.openshiftio` to `.openshift` was a mistake on Vert.x side, as Launcher still expects `.openshiftio`: https://github.com/fabric8-launcher/launcher-application/blob/master/core/core-impl/src/main/java/io/fabric8/launcher/core/impl/steps/OpenShiftSteps.java#L108

Not gonna merge this, at least unless Launcher changes :-)

**Comment by Ladicek** [comment]
Please use your fork of this repository for PRs; don't put branches directly in this repo.

**Comment by akoniar** [comment]
@Ladicek thanks for the info :-).

**Pull request closed without merging**
